### ISSUE TITLE
Add Color component to Vertex

### ISSUE THREAD

**Issue by zilmarinen** [nicklockwood/Euclid#62]
@nicklockwood I was curious as to how feasible it would be to add a color component to the `Vertex` to allow for per vertex colors so I have made a [PR](https://github.com/nicklockwood/Euclid/pull/61) that is a WIP to add this functionality.

I think the concerns here are mainly how to maintain backward compatibility whilst changing the `Vertex` decoding/encoding where both texture coordinates and color components can be omitted. The only caveat for this change is that to add a color to a vertex the texture coordinates must also be provided due to the nature of the unkeyed container decoding. This suits my needs but may not be inline with your overall vision for Euclid.

I have not yet amended the `SCNGeometry` mesh generation to include the color vertex data as I wanted to run this past you first before fiddling with the internals.

**Comment by nicklockwood** [comment]
@CaptainRedmuff this looks like a great addition, thanks! I think your solution to the optional vertex/color problem makes sense.

Just a couple of points:

1) I already have a Color struct in https://github.com/nicklockwood/ShapeScript, so it probably makes sense to port that over to Euclid rather than introducing a slightly different one.

2) Would you mind installing SwiftFormat (`brew install swiftformat`, or you can get it from https://github.com/nicklockwood/SwiftFormat) as it will ensure your PR follows the project coding style (it runs automatically when you run the Euclid unit tests)

Thanks!

**Comment by nicklockwood** [comment]
Landed in 0.5.16
